apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: edademo-dev-env
  namespace: openshift-gitops
spec:
  destination:
    namespace: edademo-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/edademo-dev/env/overlays
    repoURL: https://github.com/jbcodeforce/eda-demo-order-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
