apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app-eda-demo-order-ms
  name: edademo-dev-services-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: edademo-dev
    server: https://kubernetes.default.svc
  project: edademo
  source:
    path: environments/edademo-dev/apps/services/overlays
    repoURL: https://github.com/jbcodeforce/eda-demo-order-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
