apiVersion: microcks.github.io/v1alpha1
kind: MicrocksInstall
metadata:
  name: eda-microcks
  namespace: edademo-dev
spec:
  name: eda-microcks
  version: 1.4.1
  microcks:
    replicas: 1
  postman:
    replicas: 1
  keycloak:
    install: true
    persistent: true
    volumeSize: 1Gi
  mongodb:
    install: true
    persistent: true
    volumeSize: 2Gi