apiVersion: eventstreams.ibm.com/v1alpha1
kind: KafkaConnector
metadata:
  name: cos-sink-connector
  labels:
    eventstreams.ibm.com/cluster: eda-kconnect-cluster
spec:
  class: com.ibm.eventstreams.connect.cossink.COSSinkConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    topics: eda-demo.orders
    cos.api.key: ${env:IBM_COS_API_KEY}
    cos.bucket.location: ${env:IBM_COS_BUCKET_LOCATION}
    cos.bucket.name: ${env:IBM_COS_BUCKET_NAME}
    cos.service.crn: ${env:IBM_COS_CRN}
    cos.object.records: 5
    cos.bucket.resiliency: ${env:IBM_COS_RESILIENCY}
    # As try to have exactly one delivery: cos.object.deadline.seconds: 5
    cos.object.interval.seconds: 5
    # The connector uses the following scheme to name Cloud Object Storage objects:
    # topic/partition/firstoffset-lastoffset