apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: edademo-cicd
spec:
  namespaceSelector: {}
  podTemplate: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: github-push-binding
    interceptors:
    - github:
        secretRef:
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'jbcodeforce/eda-demo-order-gitops')
        overlays:
        - expression: body.ref.split('/')[2]
          key: ref
    name: ci-dryrun-from-push
    template:
      ref: ci-dryrun-from-push-template
  - bindings:
    - ref: edademo-dev-app-eda-demo-order-ms-eda-demo-order-ms-binding
    - ref: github-push-binding
    interceptors:
    - github:
        secretRef:
          secretKey: webhook-secret-key
          secretName: webhook-secret-edademo-dev-eda-demo-order-ms
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'jbcodeforce/eda-demo-order-ms')
        overlays:
        - expression: body.ref.split('/')[2]
          key: ref
    name: app-ci-build-from-push-eda-demo-order-ms
    template:
      ref: app-ci-template
status:
  configuration:
    generatedName: ""
