apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaConnect
metadata:
  name: eda-kconnect-cluster
  annotations:
    eventstreams.ibm.com/use-connector-resources: "true"
spec:
  version: 2.8.1
  replicas: 1
  bootstrapServers: es-demo-kafka-bootstrap.cp4i-eventstreams.svc:9093
  image: quay.io/ibmcase/eda-kconnect-cluster-image:latest
  
  template:
    pod:
      imagePullSecrets: []
      metadata:
        annotations:
          productChargedContainers: eda-kconnect-cluster-connect
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productID: 2a79e49111f44ec3acd89608e56138f5
          productName: IBM Event Streams for Non Production
          productVersion: 10.5.0
          productMetric: VIRTUAL_PROCESSOR_CORE
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          cloudpakName: IBM Cloud Pak for Integration
          cloudpakVersion: 2021.4.1
          productCloudpakRatio: "2:1"
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
  imagePullPolicy: Always
  externalConfiguration:
    env:
      - name: IBM_COS_API_KEY
        valueFrom:
          secretKeyRef:
            name: cos-creds
            key: cos.api.key
      - name: IBM_COS_BUCKET_LOCATION
        valueFrom:
          secretKeyRef:
            name: cos-creds
            key: cos.bucket.location
      - name: IBM_COS_BUCKET_NAME
        valueFrom:
          secretKeyRef:
            name: cos-creds
            key: cos.bucket.name
      - name: IBM_COS_RESILIENCY
        valueFrom:
          secretKeyRef:
            name: cos-creds
            key: cos.bucket.resiliency
      - name: IBM_COS_CRN
        valueFrom:
          secretKeyRef:
            name: cos-creds
            key: cos.service.crn
  tls:
    trustedCertificates:
      - secretName: es-demo-cluster-ca-cert
        certificate: ca.crt
  authentication:
    type: tls
    certificateAndKey:
      certificate: user.crt
      key: user.key
      secretName: es-tls-user
