apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: eda-demo.orders
  namespace: cp4i-eventstreams
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 3 
  replicas: 3

apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: eda-demo.order.metrics
  namespace: cp4i-eventstreams
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1 
  replicas: 1


apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: eda-demo.order.dlq
  namespace: cp4i-eventstreams
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1 
  replicas: 1